name: Seventeenth Workflow
on: 
  workflow_dispatch:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text title"
        required: false
jobs:
  call-workflow:
    uses: ./.github/workflows/workflow.yml
    with:
      title: ${{ inputs.title }}
  call-external-workflow:
    uses: CRIK0VA/workflows/.github/workflows/workflow.yml@main
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}